import { Inter } from 'next/font/google';
import { Header } from '../components/header';
import './global.css';

export const metadata = {
  title: 'Welcome to client',
  description: 'Generated by create-nx-workspace',
};

const inter = Inter({ subsets: ['latin'] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${inter.className} h-full w-full overflow-hidden text-center`}
    >
      <body className="flex h-full w-full flex-col overflow-hidden">
        <Header />
        <div className="flex h-full w-full flex-col overflow-hidden p-2">
          {children}
        </div>
      </body>
    </html>
  );
}
